name: Simple manual workflow - Three Env

on:
  workflow_dispatch:
	push:
	branches:
      - main

jobs:
	env:
	  AZURE_WEBAPP_NAME: TestCoreApp
	  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
  DEV:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      
      - name: Restore
        run: dotnet restore ./WebApp/WebApp.sln
      
      - name: Build
        run: dotnet build ./WebApp/WebApp.sln --configuration Release --no-restore
      
      - name: Publish
        run: dotnet publish ./WebApp/WebApp.sln --configuration Release --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deployment
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.WebCoreApp }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
